services:
  postgres-db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgresql
    restart: always
    command: >
      postgres
      -c max_locks_per_transaction=128
      -c shared_preload_libraries=pg_partman_bgw,timescaledb
      -c pg_partman_bgw.role=postgres
      -c pg_partman_bgw.dbname=postgres,test_database
      -c pg_partman_bgw.interval=3600
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "0000"
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
      TZ: Asia/Taipei
      PGTZ: Asia/Taipei
    volumes:
      - postgres-db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres-network
  pgbouncer:
    image: bitnami/pgbouncer:1.24.1
    container_name: pgbouncer
    restart: always
    environment:
      POSTGRESQL_HOST: postgres-db
      POSTGRESQL_PORT: 5432
      POSTGRESQL_DATABASE: postgres
      POSTGRESQL_USER: postgres
      POSTGRESQL_PASSWORD: "0000"
      PGBOUNCER_USER: pgbouncer
      PGBOUNCER_PASSWORD: "0000"
      PGBOUNCER_PORT: 6432
    volumes:
      - ./pgBouncerConfig:/bitnami/pgbouncer/conf
    ports:
      - "6432:6432"
    networks:
      - postgres-network
volumes:
  postgres-db_data: 
networks:
  postgres-network:
    driver: bridge